# Generated by Django 5.0.7 on 2024-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millennium', models.SmallIntegerField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
