# Generated by Django 5.0.7 on 2024-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space_Marines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemarines',
            name='symbol',
            field=models.ImageField(default='default_symbol.jpg', upload_to='Space_Marines/images/'),
        ),
    ]
