# Generated by Django 5.0.7 on 2024-10-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space_Marines', '0002_spacemarines_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemarines',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spacemarines',
            name='image',
            field=models.ImageField(default='default_icon.png', upload_to='Space_Marines/images/'),
        ),
        migrations.AlterField(
            model_name='spacemarines',
            name='symbol',
            field=models.ImageField(default='default_image.jpg', upload_to='Space_Marines/images/'),
        ),
    ]
